name: Run Unity Tests
on: [pull_request, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: runTests
        uses: trudeaua21/unity-test-runner@main
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ./com.trudeaua.easyaccessibility
          unityVersion: "2020.3.0f1"
          testMode: all
          packageMode: true