name: Run Unity Tests
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: runTests
        uses: trudeaua21/unity-test-runner
        with:
          projectPath: ./com.trudeaua.easyaccessibility
          unityVersion: "2020.3.0f1"
          testMode: all
          packageMode: true